services:
  fireaid_web:
    container_name: fireaid_web
    build:
      context: ./fireaid_web/
      dockerfile: docker/Dockerfile
    volumes:
      - ./fireaid_web/src:/var/web/src
      - ./fireaid_web/public:/var/web/public
    depends_on:
      - mongo
      - firemcp
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal=host-gateway"

  firemcp:
    build:
      context: ./FireMCP
    depends_on:
      - mongo
    env_file:
      - .env
    container_name: firemcp
    restart: always
    ports:
      - "8081:8081"

  rag-service:
    build:
      context: ./llm-app
    env_file:
      - .env
    container_name: rag-service 
    restart: always
    ports:
      - "8000:8000"
     
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    command: --port 27018
    ports:
      - "27018:27018" 
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
