"use client";

import { useState } from "react";
import FireAIDSidebar from "@/components/layout/FireAIDSidebar";
import { FileText, Download, RefreshCw, Send } from "lucide-react";
import { callFireTool } from "@/lib/mcpClient";

type ReportData = {
  report: string;
  stats: { totalFires: number; totalAcres: number; topCause: string; topFuel: string; topYear: string };
};

const SUGGESTED = [
  "Generate a report on Alaska wildfires in 2022",
  "Report on lightning fires from 2020 to 2024",
  "Summarize prescribed burns in the last 5 years",
  "Annual wildfire trend report 2015-2024",
];

export default function ReportsPage() {
  const [input, setInput]         = useState("");
  const [loading, setLoading]     = useState(false);
  const [report, setReport]       = useState<ReportData | null>(null);
  const [error, setError]         = useState<string | null>(null);

  async function generate(text?: string) {
    const msg = text ?? input.trim();
    if (!msg || loading) return;
    setInput(msg);
    setLoading(true); setError(null); setReport(null);

    try {
      // Step 1: fetch fire data via MCP
      const mcpRes = await fetch("/api/mcp/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: msg }),
      });
      const mcpData = await mcpRes.json();
      if (!mcpRes.ok) throw new Error(mcpData.error ?? "Failed to fetch data");

      const fires = mcpData.results ?? [];
      if (!fires.length) throw new Error("No fire data found for this query");

      // Step 2: generate AI report
      const repRes = await fetch("/api/mcp/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ fires, query: msg }),
      });
      const repData = await repRes.json();
      if (!repRes.ok) throw new Error(repData.error ?? "Failed to generate report");

      setReport(repData);
    } catch (e: any) {
      setError(e?.message ?? "Error");
    } finally {
      setLoading(false);
    }
  }

  function downloadPDF() {
    if (!report) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Wildfire Report</title>
  <style>
    body { font-family: helvetica, arial, sans-serif; margin: 40px; color: #222; }
    h1 { color: #1e293b; font-size: 24px; margin-bottom: 4px; }
    .meta { color: #888; font-size: 11px; margin-bottom: 16px; }
    .stats { background: #f97316; color: white; padding: 12px 16px; border-radius: 8px; font-size: 12px; font-weight: bold; margin-bottom: 20px; }
    h3 { color: #f97316; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-top: 20px; margin-bottom: 6px; border-bottom: 1px solid #fed7aa; padding-bottom: 4px; }
    p { font-size: 11px; color: #334155; line-height: 1.7; margin: 2px 0; }
    .footer { margin-top: 40px; font-size: 9px; color: #aaa; border-top: 1px solid #eee; padding-top: 8px; }
  </style>
</head>
<body>
  <h1>Wildfire Incident Report</h1>
  <div class="meta">Generated: ${new Date().toLocaleDateString()} | FireAID System | UAF Data/AI Lab</div>
  <div class="stats">${report.stats.totalFires} Fires &nbsp;|&nbsp; ${(report.stats.totalAcres/1000).toFixed(1)}K Acres &nbsp;|&nbsp; Top Cause: ${report.stats.topCause} &nbsp;|&nbsp; Peak Year: ${report.stats.topYear}</div>
  ${report.report.split("\n").map(line => {
    if (!line.trim()) return "<br/>";
    if (/^[A-Z][A-Z\s&]+$/.test(line.trim()) && line.trim().length > 3)
      return `<h3>${line.trim()}</h3>`;
    return `<p>${line.replace(/^[-•*]\s*/, "• ")}</p>`;
  }).join("")}
  <div class="footer">Generated by FireAID | UAF Data/AI Lab | For research purposes only</div>
</body>
</html>`;
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  }

  return (
    <div className="grid min-w-0 grid-cols-1 gap-6 xl:grid-cols-[288px_minmax(0,1fr)]">
      <FireAIDSidebar active="reports" />

      <div className="min-w-0 space-y-4">
        {/* Header */}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-500 text-white">
              <FileText size={18} />
            </div>
            <div>
              <div className="text-xl font-bold text-slate-900">AI Report Generator</div>
              <div className="text-xs text-slate-500">Describe what you want — AI queries the database and generates a professional PDF report</div>
            </div>
          </div>

          <div className="mt-4 flex gap-2">
            <input
              className="flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-1 focus:ring-indigo-100 placeholder:text-slate-400"
              placeholder='e.g. "Generate a report on Alaska wildfires in 2022"'
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && generate()}
              disabled={loading}
            />
            <button
              className="rounded-xl bg-indigo-500 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-600 disabled:opacity-50 flex items-center gap-2"
              onClick={() => generate()}
              disabled={loading || !input.trim()}
            >
              {loading ? <RefreshCw size={14} className="animate-spin" /> : <Send size={14} />}
              {loading ? "Generating..." : "Generate"}
            </button>
          </div>

          {!report && !loading && (
            <div className="mt-3 flex flex-wrap gap-2">
              {SUGGESTED.map(q => (
                <button key={q} className="rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 transition" onClick={() => generate(q)}>
                  {q}
                </button>
              ))}
            </div>
          )}
        </div>

        {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}

        {loading && (
          <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-8 text-center shadow-sm">
            <RefreshCw size={24} className="mx-auto text-indigo-400 animate-spin mb-3" />
            <div className="text-sm font-semibold text-indigo-700">Querying database and generating report...</div>
            <div className="text-xs text-indigo-500 mt-1">This may take 10-15 seconds</div>
          </div>
        )}

        {report && (
          <>
            {/* Stats */}
            <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
              <StatCard label="Total Fires"  value={String(report.stats.totalFires)} />
              <StatCard label="Total Acres"  value={`${(report.stats.totalAcres/1000).toFixed(1)}K`} />
              <StatCard label="Top Cause"    value={report.stats.topCause} small />
              <StatCard label="Top Fuel"     value={report.stats.topFuel} small />
              <StatCard label="Peak Year"    value={report.stats.topYear} />
            </div>

            {/* Report preview */}
            <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">
              <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3">
                <div className="text-sm font-bold text-slate-900">Report Preview</div>
                <button
                  className="flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2 text-xs font-semibold text-white hover:bg-indigo-600 disabled:opacity-50"
                  onClick={downloadPDF}
                  
                >
                  <Download size={12} />
                  "Download PDF"
                </button>
              </div>
              <div className="p-5">
                <div className="prose prose-sm max-w-none">
                  {report.report.split("\n").map((line, i) => {
                    if (!line.trim()) return <div key={i} className="h-2" />;
                    if (/^[A-Z][A-Z\s&]+$/.test(line.trim()) && line.trim().length > 3) {
                      return <h3 key={i} className="text-sm font-bold text-orange-500 mt-4 mb-1 uppercase tracking-wide">{line}</h3>;
                    }
                    return <p key={i} className="text-xs text-slate-700 leading-relaxed">{line.replace(/^[-•*]\s*/, "• ")}</p>;
                  })}
                </div>
              </div>
            </div>
          </>
        )}

        {!report && !loading && !error && (
          <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-12 text-center shadow-sm">
            <FileText size={32} className="mx-auto text-slate-300 mb-3" />
            <div className="text-sm font-semibold text-slate-500">No report yet</div>
            <div className="text-xs text-slate-400 mt-1">Describe your report above and click Generate</div>
          </div>
        )}
      </div>
    </div>
  );
}

function StatCard({ label, value, small }: { label: string; value: string; small?: boolean }) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
      <div className="text-[11px] font-semibold text-slate-500">{label}</div>
      <div className={`mt-0.5 font-bold text-slate-900 truncate ${small ? "text-xs" : "text-lg"}`}>{value}</div>
    </div>
  );
}