name: Display Fireaid Home Directory

permissions:
    contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: [self-hosted]
        steps:
            - name: List Home 
              run: |
                cd /home/fireaid/chromadb
                echo "Path: $(pwd)"
                echo $(ls)
